version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    # ignore:
    #   - dependency-name: "flask"
    #     versions: ["1.1.0"]