name: Python Flask CI

on:
  push:
    branches:
      - main
      - week3
  pull_request:
    branches:
      - main
      - week3

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Install dependencies (tox)
      - name: Install tox and other packages
        run: pip install tox

      # Run tox (tests and coverage)
      - name: Run tox
        run: tox -e py

      # SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
